# Generated by Django 5.2.3 on 2025-06-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommApp', '0002_alter_cart_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dhl_tracking_number',
        ),
    ]
